/*
 *  @file  : SlxElevateBridge.h
 *  @author: luteng
 *  @date  : 2015-08-07 17:41:24.764
 *  @note  : Generated by SlxTemplates
 */

#ifndef _SLXELEVATEBRIDGE_H
#define _SLXELEVATEBRIDGE_H

#include <Windows.h>

int WINAPI ElevateAndRunA(LPCSTR lpCommand, LPCSTR lpArguments, LPCSTR lpDirectory, int nShowCmd);
int WINAPI ElevateAndRunW(LPCWSTR lpCommand, LPCWSTR lpArguments, LPCWSTR lpDirectory, int nShowCmd);

#ifdef UNICODE
#define ElevateAndRun ElevateAndRunW
#else
#define ElevateAndRun ElevateAndRunA
#endif

#endif /* _SLXELEVATEBRIDGE_H */